name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones disabled for SonarQube

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: npm run build:api

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type checking
        run: npm run typecheck

      - name: Run unit tests
        run: npm test -- --coverage --passWithNoTests

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

      - name: SonarQube Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Build application
        run: npm run build

#  Lighthouse CI Testing (disabled until credentials are configured)
#  lighthouse:
#    runs-on: ubuntu-latest
#    needs: ci
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '18'
#          cache: 'npm'
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Build application
#        run: npm run build
#
#      - name: Run Lighthouse CI
#        run: npx lhci autorun
#        env:
#          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
#
#      - name: Upload Lighthouse results
#        uses: actions/upload-artifact@v3
#        with:
#          name: lighthouse-results
#          path: .lighthouseci
#        if: always()


#  Security Audit (Snyk step disabled until credentials are configured)
#  security:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Run npm audit
#        run: npm audit --audit-level=moderate
#
#      # - name: Run Snyk Security Test
#      #   uses: snyk/actions/node@master
#      #   env:
#      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#      #   with:
#      #     args: --severity-threshold=high
